### ISSUE TITLE
'*Attribute' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by xvwvx** [DagobertDev/CityBuilder#40]
NavigationDestinationSystem.cs(11, 71): [CS0246] The type or namespace name 'NavigationAgent2D' could not be found (are you missing a using directive or an assembly reference?)
  NavigationInitSystem.cs(8, 17): [CS0246] The type or namespace name 'NavigationAgent2D' could not be found (are you missing a using directive or an assembly reference?)
  NavigationDestinationSystem.cs(10, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  NavigationInitSystem.cs(11, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  NavigationInitSystem.cs(11, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  CollisionSystem.cs(27, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  CollisionSystem.cs(27, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  ConstructionSystem.cs(12, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  ConstructionSystem.cs(12, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  CollisionSystem.cs(28, 41): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  CollisionSystem.cs(28, 48): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  NavigationDestinationSystem.cs(11, 30): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  NavigationDestinationSystem.cs(11, 37): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  SizeFromSpriteSystem.cs(11, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  SizeFromSpriteSystem.cs(11, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  CollisionSystem.cs(29, 4): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  CollisionSystem.cs(29, 11): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  SizeFromSpriteSystem.cs(12, 48): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  SizeFromSpriteSystem.cs(12, 55): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  NavigationSystem.cs(15, 50): [CS0246] The type or namespace name 'NavigationAgent2D' could not be found (are you missing a using directive or an assembly reference?)
  CollisionSystem.cs(29, 35): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  CollisionSystem.cs(29, 42): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  NavigationSystem.cs(14, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  NavigationSystem.cs(14, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  ConstructionProgressVisualisationSystem.cs(10, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  ConstructionProgressVisualisationInitSystem.cs(12, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  ConstructionProgressVisualisationInitSystem.cs(13, 3): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  ConstructionProgressVisualisationSystem.cs(11, 30): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  ConstructionProgressVisualisationSystem.cs(11, 37): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  ConstructionProgressVisualisationSystem.cs(12, 4): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  ConstructionProgressVisualisationSystem.cs(12, 11): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  NavigationMeshSystem.cs(15, 3): [CS0122] 'ConstructorParameterAttribute' is inaccessible due to its protection level
  MovementRotationSystem.cs(10, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  MovementRotationSystem.cs(10, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  MovementRotationSystem.cs(11, 48): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  MovementRotationSystem.cs(11, 55): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  NavigationMeshSystem.cs(28, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  NavigationMeshSystem.cs(28, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  NavigationMeshSystem.cs(29, 69): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  NavigationMeshSystem.cs(29, 76): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  ResourcePileRemovalSystem.cs(10, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  ResourcePileRemovalSystem.cs(10, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  ResourcePileVisualisationSystem.cs(12, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  ResourcePileVisualisationSystem.cs(12, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  GrowthVisualisationSystem.cs(12, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  SpriteCreationSystem.cs(18, 3): [CS0122] 'ConstructorParameterAttribute' is inaccessible due to its protection level
  SpriteCreationSystem.cs(21, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  SpriteCreationSystem.cs(21, 11): [CS0122] 'UseBufferAttribute' is inaccessible due to its protection level
  GrowthVisualisationSystem.cs(13, 48): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  GrowthVisualisationSystem.cs(13, 55): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  SpriteRotationSystem.cs(9, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  SpritePositionSystem.cs(10, 3): [CS0122] 'UpdateAttribute' is inaccessible due to its protection level
  SpriteRotationSystem.cs(10, 30): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  SpriteRotationSystem.cs(10, 37): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  SpritePositionSystem.cs(11, 48): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level
  SpriteRotationSystem.cs(10, 65): [CS0122] 'AddedAttribute' is inaccessible due to its protection level
  SpriteRotationSystem.cs(10, 72): [CS0122] 'ChangedAttribute' is inaccessible due to its protection level

**Comment by DagobertDev** [comment]
Thanks for the report.
It looks like all errors are from the CityBuilder project and none from CityBuilder.Core. project.
Do you have the Godot Engine installed and your IDE configured to use it? Not having Godot installed could be the issue.

**Comment by xvwvx** [comment]
Thanks for the answer, solved the problem using godot 3.5
